# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Latest Blog posts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: 
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    - name: Update Python Script
      run: |
        python show_blog_daily.py
    - name: Update README.md file
      run: |
        git add .
        git diff
        git config --local user.email "jjys9047@naver.com"
        git config --local user.name "Daikoku"
        git commit --allow-empty -m "Update README.md"
        git push
